apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-rabbitmq
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: rabbitmq.scdf.asc-test.net
    http:
      paths:       
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: rabbitmq
            port: 
              number: 5672